### ISSUE TITLE
Docker error at start

### ISSUE THREAD

**Issue by danlo315** [wouterdebie/locast2tuner#47] opened 2021-05-10 04:01 UTC
Hello - the docker container just started this error on startup:

May 10 03:57:56.184 INFO Using cached FCC facilities at /root/.locast2tuner/facilities,
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("missing field `showType`", line: 1, column: 205453) }', src/service/mod.rs:333:10

**Comment by wouterdebie** [comment] 2021-05-10 04:02
Duplicate of #46

**Closed as completed** 2021-05-10 04:01 UTC
